listenAddr = ":7569"


[programs]

    [programs.cat]
    cmd="cat"
    maxMem="10MiB"
    timeout=""
    poolSize=10
    expectPrefix=""

    [programs.java]
    cmd="/usr/bin/java -jar cmd/java/target/execjar-0.0.1-exec.jar"
    maxMem="50MiB"
    timeout="3s"
    poolSize=3
    expectPrefix=""